FROM bearstech/debian:bullseye

RUN set -eux \
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
            build-essential \
            ca-certificates \
            git \
            mercurial \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/*

# generated labels

ARG GIT_VERSION
ARG GIT_DATE
ARG BUILD_DATE

LABEL \
    com.bearstech.image.revision_date=${GIT_DATE} \
    org.opencontainers.image.authors=Bearstech \
    org.opencontainers.image.revision=${GIT_VERSION} \
    org.opencontainers.image.created=${BUILD_DATE} \
    org.opencontainers.image.url=https://github.com/factorysh/docker-debian \
    org.opencontainers.image.source=https://github.com/factorysh/docker-debian/blob/${GIT_VERSION}/Dockerfile.dev
